### PR TITLE
Update Cookies (26.04.2018)

### LINKED ISSUE #7375: culturapoloneza.ro/pl
Cookies

### PR DESCRIPTION
**Pull request by hawkeye116477**
Fix #7375, #7238

### CODE REVIEW

**Comment by jspenguin2017** [comment]
FYI the scriptlet is renamed to `nano-click-elements-onready.js` to reflect what it does, remove all elements that match the selector. 
I'll PR the snippet to uAssets, not sure if they'll accept it.

**Comment by jspenguin2017** [comment]
After discussing with gorhill, I decided to make this script snippet privileged as clicking on elements can be dangerous. The script snippet is only accessible from NanoFilters and nowhere else. 

On uBO side, the proposal is rejected, so uBO won't have this.

**Comment by hawkeye116477** [comment]
Ok, so I will remove this rule.

**Comment by jspenguin2017** [comment]
Sorry for the mess, it's hard to get everyone on the same page. 

I also added another privileged script snippet that can set arbitrary cookies, so if there are tough cookie walls like this one just let me know and I'll add to the annoyance filter of Nano. 

I can't make them work on uBO due to security concerns, I can't seem to convince gorhill to add privileged script snippet system to uBO, well, I have tried...

**Pull request merged**
