### PR TITLE
Update social and cookies to version 2017092101

### LINKED ISSUE #3726: mmarocks.pl
Reklamy

### LINKED ISSUE #3729: domena.pl
Uwaga!
Strona korzysta z plików cookies. Odwiedzając nasz serwis zgadzasz się na ich przyjmowanie. Szczegółowe informacje w Polityce prywatności
Nie pokazuj komunikatu ponownie

### LINKED ISSUE #3730: mamkomputer.info
screenshot from 2017-09-18 20-35-28

### LINKED ISSUE #3740: vexel-fashion.pl
Ciastka -> `vexel-fashion.pl##.header-notice`
Social -> `vexel-fashion.pl##.contacts.row`

### LINKED ISSUE #3741: kotkowicz.pl
Social -> `kotkowicz.pl##.widget_apsc_widget, .widget_ws_fb_like_box`

### LINKED ISSUE #3744: alget.pl
Social -> `alget.pl###social_news`

### PR DESCRIPTION
**Pull request by hawkeye116477**
Fix #3726, fix #3729, fix #3730, fix #3740, fix #3741, fix #3744, #3750, #3755, #3758, #3759

### CODE REVIEW

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT Aktualizacja

**Comment by ryanbr** [comment]
lastfm.pl vs last.fm/pl/ which is current?

**Comment by hawkeye116477** [comment]
@ryanbr last.fm/pl/

**Comment by ryanbr** [comment]
Right, lastfm.pl#@#.social-sharing wouldn't work then?

**Comment by hawkeye116477** [comment]
@ryanbr Yes, it's not needed.

**Pull request merged**
